DIGITS = "0123456789"


"""TOKENS"""

TT_INT = "TT_INT"
TT_FLOAT = "FLOAT"
TT_PLUS = "PLUS"
TT_MINUS = "MINUS"
TT_DIVIDE = "DIVIDE"
TT_MUL = "MUL"
TT_LPAREN = "LPAREN"
TT_RPAREN = "RPAREN"
TT_MODULO = "MODULO"
TT_EXPO = "EXPO"
TT_EOF = "EOF"
